// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'HelloWorld': typeof import("../../components/helloWorld.vue")['default'],
    'MenuHeader': typeof import("../../components/menuHeader.vue")['default'],
    'NuxtWelcome': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue")['default'],
    'ClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default']
  }
}
export {}
